@ECHO ON
SET CURR_DIR=%CD%

SET LOCAL_MODPATH=app\code\local
SET COMMUNITY_MODPATH=app\code\community
SET CORE_MODPATH=app\code\core

SET /P PACKAGE_NAME="Package Name ? "
SET /P MODULE_NAME="Module Name ? "
SET /P CODEPOOL="CodePool ? "

FOR /F "DELIMS=" %%A IN ('WMIC OS GET LOCALDATETIME  ^| FIND "."') DO SET dt=%%A
SET YYYY=%dt:~0,4%
SET MM=%dt:~4,2%
SET DD=%dt:~6,2%
SET HH=%dt:~8,2%
SET Min=%dt:~10,2%
SET Sec=%dt:~12,2%
SET STAMP=%YYYY%-%MM%-%DD%_%HH%-%Min%-%Sec%
SET CRT_DIR=%CD%\module_%STAMP%

IF "%CODEPOOL%" == "community" (
	MD %CRT_DIR%\%COMMUNITY_MODPATH%\%PACKAGE_NAME%\%MODULE_NAME%\Block
	MD %CRT_DIR%\%COMMUNITY_MODPATH%\%PACKAGE_NAME%\%MODULE_NAME%\Model
	MD %CRT_DIR%\%COMMUNITY_MODPATH%\%PACKAGE_NAME%\%MODULE_NAME%\controllers
	MD %CRT_DIR%\%COMMUNITY_MODPATH%\%PACKAGE_NAME%\%MODULE_NAME%\sql
	MD %CRT_DIR%\%COMMUNITY_MODPATH%\%PACKAGE_NAME%\%MODULE_NAME%\etc
	MD %CRT_DIR%\%COMMUNITY_MODPATH%\%PACKAGE_NAME%\%MODULE_NAME%\data
)
IF "%CODEPOOL%" == "local" (
	MD %CRT_DIR%\%LOCAL_MODPATH%\%PACKAGE_NAME%\%MODULE_NAME%\Block
	MD %CRT_DIR%\%LOCAL_MODPATH%\%PACKAGE_NAME%\%MODULE_NAME%\Model
	MD %CRT_DIR%\%LOCAL_MODPATH%\%PACKAGE_NAME%\%MODULE_NAME%\etc
	MD %CRT_DIR%\%LOCAL_MODPATH%\%PACKAGE_NAME%\%MODULE_NAME%\controllers
	MD %CRT_DIR%\%LOCAL_MODPATH%\%PACKAGE_NAME%\%MODULE_NAME%\data
	MD %CRT_DIR%\%LOCAL_MODPATH%\%PACKAGE_NAME%\%MODULE_NAME%\sql
)
IF "%CODEPOOL%" == "core" (
	MD %CRT_DIR%\%CORE_PATH%\%PACKAGE_NAME%\%MODULE_NAME%\Block
	MD %CRT_DIR%\%CORE_PATH%\%PACKAGE_NAME%\%MODULE_NAME%\Model
	MD %CRT_DIR%\%CORE_PATH%\%PACKAGE_NAME%\%MODULE_NAME%\etc
	MD %CRT_DIR%\%CORE_PATH%\%PACKAGE_NAME%\%MODULE_NAME%\controllers
	MD %CRT_DIR%\%CORE_PATH%\%PACKAGE_NAME%\%MODULE_NAME%\data
	MD %CRT_DIR%\%CORE_PATH%\%PACKAGE_NAME%\%MODULE_NAME%\sql
)
PAUSE
::FOR /d %A IN ("e:\corporate folder\*") DO MD ""%A\2015"
